name: Post to LinkedIn (Twice Daily)

on:
  schedule:
    - cron: "0 10 * * *"   # 11:00 AM IST (5:30 ahead of UTC)
    - cron: "30 17 * * *" # 7:00 PM IST (1:30 PM UTC)
  workflow_dispatch:      # Manual run option

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_URN: ${{ secrets.LINKEDIN_URN }}

        run: python dailyLinkedinPost.py
